import type { PatternSpec } from './index.js';

export const fbisePatterns: PatternSpec[] = [
  {
    id: 'fbise-ssc-physics-paper',
    name: 'FBISE SSC Physics — Annual Paper',
    board: 'FBISE',
    format: 'paper',
    grade: 9,
    subject: 'Physics',
    totalMarks: 60,
    sections: [
      {
        type: 'mcq',
        title: 'Section A',
        instructions: 'Choose the correct option. Each question carries 1 mark.',
        questionCount: 12,
        marksPerQuestion: 1,
      },
      {
        type: 'short',
        title: 'Section B',
        instructions: 'Answer briefly. Each question carries 2 marks.',
        questionCount: 12,
        marksPerQuestion: 2,
      },
      {
        type: 'long',
        title: 'Section C',
        instructions: 'Answer in detail. Each question carries 8 marks.',
        questionCount: 3,
        marksPerQuestion: 8,
      },
    ],
    notes: 'Approximate FBISE SSC physics pattern. Tune to actual examination scheme.',
  },
  {
    id: 'fbise-ssc-paper',
    name: 'FBISE SSC — Annual Paper (Generic)',
    board: 'FBISE',
    format: 'paper',
    grade: 9,
    subject: null,
    totalMarks: 75,
    sections: [
      {
        type: 'mcq',
        title: 'Section A',
        instructions: 'Choose the correct option.',
        questionCount: 15,
        marksPerQuestion: 1,
      },
      {
        type: 'short',
        title: 'Section B',
        instructions: 'Answer briefly.',
        questionCount: 12,
        marksPerQuestion: 3,
      },
      {
        type: 'long',
        title: 'Section C',
        instructions: 'Answer in detail.',
        questionCount: 3,
        marksPerQuestion: 8,
      },
    ],
  },
  {
    id: 'fbise-ssc-midterm',
    name: 'FBISE SSC — Mid-term',
    board: 'FBISE',
    format: 'midterm',
    grade: 9,
    subject: null,
    totalMarks: 40,
    sections: [
      {
        type: 'mcq',
        title: 'Section A',
        instructions: 'Choose the correct option.',
        questionCount: 8,
        marksPerQuestion: 1,
      },
      {
        type: 'short',
        title: 'Section B',
        instructions: 'Answer briefly.',
        questionCount: 6,
        marksPerQuestion: 2,
      },
      {
        type: 'long',
        title: 'Section C',
        instructions: 'Answer in detail.',
        questionCount: 2,
        marksPerQuestion: 10,
      },
    ],
  },
  {
    id: 'fbise-ssc-quiz',
    name: 'FBISE SSC — Class Quiz',
    board: 'FBISE',
    format: 'quiz',
    grade: 9,
    subject: null,
    totalMarks: 15,
    sections: [
      {
        type: 'mcq',
        title: 'Quick MCQs',
        instructions: 'Choose the correct option.',
        questionCount: 10,
        marksPerQuestion: 1,
      },
      {
        type: 'short',
        title: 'Short Answer',
        instructions: 'Answer briefly.',
        questionCount: 5,
        marksPerQuestion: 1,
      },
    ],
  },
  {
    id: 'fbise-hssc-paper',
    name: 'FBISE HSSC — Annual Paper',
    board: 'FBISE',
    format: 'paper',
    grade: 11,
    subject: null,
    totalMarks: 85,
    sections: [
      {
        type: 'mcq',
        title: 'Section A',
        instructions: 'Choose the correct option.',
        questionCount: 17,
        marksPerQuestion: 1,
      },
      {
        type: 'short',
        title: 'Section B',
        instructions: 'Answer briefly.',
        questionCount: 14,
        marksPerQuestion: 3,
      },
      {
        type: 'long',
        title: 'Section C',
        instructions: 'Answer in detail.',
        questionCount: 4,
        marksPerQuestion: 8,
      },
    ],
  },
];
