import type { PatternSpec } from './index.js';

export const punjabPatterns: PatternSpec[] = [
  {
    id: 'punjab-ssc-paper',
    name: 'Punjab Board SSC — Annual Paper',
    board: 'PUNJAB',
    format: 'paper',
    grade: 9,
    subject: null,
    totalMarks: 75,
    sections: [
      {
        type: 'mcq',
        title: 'Objective',
        instructions: 'Encircle the correct option.',
        questionCount: 12,
        marksPerQuestion: 1,
      },
      {
        type: 'short',
        title: 'Subjective — Short',
        instructions: 'Answer concisely. Each question carries 2 marks.',
        questionCount: 14,
        marksPerQuestion: 2,
      },
      {
        type: 'long',
        title: 'Subjective — Long',
        instructions: 'Answer in detail.',
        questionCount: 3,
        marksPerQuestion: 5,
      },
    ],
    notes: 'Generic Punjab Board 9th class pattern. Adjust per subject.',
  },
  {
    id: 'punjab-ssc-midterm',
    name: 'Punjab Board SSC — Mid-term',
    board: 'PUNJAB',
    format: 'midterm',
    grade: 9,
    subject: null,
    totalMarks: 40,
    sections: [
      {
        type: 'mcq',
        title: 'Objective',
        instructions: 'Encircle the correct option.',
        questionCount: 8,
        marksPerQuestion: 1,
      },
      {
        type: 'short',
        title: 'Short Questions',
        instructions: 'Answer concisely.',
        questionCount: 7,
        marksPerQuestion: 2,
      },
      {
        type: 'long',
        title: 'Long Questions',
        instructions: 'Answer in detail.',
        questionCount: 2,
        marksPerQuestion: 9,
      },
    ],
  },
  {
    id: 'punjab-ssc-assignment',
    name: 'Punjab Board SSC — Assignment',
    board: 'PUNJAB',
    format: 'assignment',
    grade: 9,
    subject: null,
    totalMarks: 25,
    sections: [
      {
        type: 'short',
        title: 'Conceptual Questions',
        instructions: 'Answer all questions.',
        questionCount: 5,
        marksPerQuestion: 3,
      },
      {
        type: 'long',
        title: 'Application Questions',
        instructions: 'Show all working.',
        questionCount: 2,
        marksPerQuestion: 5,
      },
    ],
  },
  {
    id: 'punjab-ssc-quiz',
    name: 'Punjab Board SSC — Class Quiz',
    board: 'PUNJAB',
    format: 'quiz',
    grade: 9,
    subject: null,
    totalMarks: 10,
    sections: [
      {
        type: 'mcq',
        title: 'Quiz',
        instructions: 'Encircle the correct option.',
        questionCount: 10,
        marksPerQuestion: 1,
      },
    ],
  },
  {
    id: 'punjab-hssc-paper',
    name: 'Punjab Board HSSC — Annual Paper',
    board: 'PUNJAB',
    format: 'paper',
    grade: 11,
    subject: null,
    totalMarks: 85,
    sections: [
      {
        type: 'mcq',
        title: 'Objective',
        instructions: 'Encircle the correct option.',
        questionCount: 17,
        marksPerQuestion: 1,
      },
      {
        type: 'short',
        title: 'Subjective — Short',
        instructions: 'Answer concisely.',
        questionCount: 14,
        marksPerQuestion: 3,
      },
      {
        type: 'long',
        title: 'Subjective — Long',
        instructions: 'Answer in detail.',
        questionCount: 4,
        marksPerQuestion: 8,
      },
    ],
  },
];
